Repository edgelesssys/marblerun, pull requests merged in 2025-01, with the labels that each got.

#782 Fix Marble verification with Coordinator root certificate
  cmd/marble-test/main.go
  coordinator/core/marbleapi.go
  coordinator/core/marbleapi_test.go
  marble/premain/occlum.go
  test/integration_test.go
  test/manifests.go
Labels: bug fix

#784 Support injection of Coordinator root and intermediate certificates into Marble environment
  coordinator/core/marbleapi.go
  coordinator/core/marbleapi_test.go
  coordinator/manifest/manifest.go
  coordinator/manifest/manifest_test.go
  docs/docs/workflows/define-manifest.md
Labels: feature

#785 coordinator: threshold manifest update support
  coordinator/manifest/manifest.go
  coordinator/manifest/manifest_test.go
  docs/docs/workflows/define-manifest.md
  docs/docs/workflows/update-manifest.md
Labels: no changelog

#788 coordinator: remove obsolete GetRecoveryData
  coordinator/clientapi/clientapi.go
  coordinator/recovery/recovery.go
  coordinator/recovery/single.go
Labels: no changelog

#789 cli: fix missing newline when performing multi party recovery
  cli/internal/cmd/recover.go
Labels: no changelog

#786 coordinator: add debug logging
  cmd/coordinator/enclavemain.go
  cmd/coordinator/main.go
  cmd/coordinator/run.go
  coordinator/clientapi/clientapi_test.go
  coordinator/clientapi/legacy_test.go
  coordinator/constants/constants.go
  coordinator/core/certificate_test.go
  coordinator/core/core.go
  coordinator/core/core_test.go
  coordinator/core/marbleapi_test.go
  coordinator/core/metrics_test.go
  coordinator/seal/noenclavesealer.go
  coordinator/seal/seal.go
  coordinator/seal/seal_test.go
  coordinator/server/metrics_test.go
  coordinator/store/stdstore/stdstore.go
  coordinator/store/stdstore/stdstore_test.go
  coordinator/store/wrapper/wrapper_test.go
  internal/logging/logging.go
  test/framework/framework.go
Labels: feature

#793 charts: allow configuration of Coordinator PVC size through helm values file
  charts/templates/coordinator.yaml
  charts/values.yaml
Labels: changelog
